/**
 * NirmaanAI Phase 21: Authoritative Pre-Calibrated Factory Intelligence State
 * Mirrors Phase 0–20 validated ML/RCA/Simulation/Financial outputs for guaranteed UI resilience.
 */

export const MOCK_FACTORY_INFO = {
  factory_id: "FAC_01",
  factory_name: "Nirmaan MSME Precision Manufacturing Plant #1",
  location: "Kolkata Industrial Corridor, West Bengal, India",
  industry: "Precision Auto Components & Textile Machinery",
  active_shift: "Shift B (Afternoon / Standard Operations)",
  operational_status: "OPERATIONAL_WITH_CRITICAL_ALERT",
  telemetry_horizon: "2026-01-21T12:00:00Z",
  total_machines: 5,
  active_machines: 5,
  critical_machines_count: 1,
  warning_machines_count: 0,
  nominal_machines_count: 4,
};

export const MOCK_KPIS = {
  factory_health_index: 83.35,
  realized_loss_inr: 73062.28,
  projected_opportunity_inr: 24320.0,
  gross_exposure_inr: 97382.28,
  avoidable_opportunity_inr: 19520.0, // Scenario D
  active_bottlenecks_count: 1,
  critical_spares_at_risk: 1,
  active_alerts_count: 3,
};

export const MOCK_MACHINES = [
  {
    machine_id: "M1",
    name: "CNC Turning Center 01",
    type: "CNC_LATHE",
    status: "HEALTHY",
    health_score: 97.47,
    failure_probability: 0.02,
    anomaly_score: 0.04,
    anomaly_threshold: 0.2405,
    is_bottleneck: false,
    cycle_ratio: 0.98,
    delayed_units: 0,
    temperature_c: 42.5,
    vibration_mms: 0.85,
    power_kw: 14.2,
    tool_wear_min: 35,
    last_service: "2026-01-10",
    rca_status: "NOMINAL",
    primary_recommendation: "CONTINUE_NOMINAL_MONITORING",
  },
  {
    machine_id: "M2",
    name: "High-Speed Spindle VMC 02",
    type: "VMC_MILLING",
    status: "CRITICAL",
    health_score: 26.88,
    failure_probability: 0.9959,
    failure_threshold: 0.91,
    anomaly_score: 0.35,
    anomaly_threshold: 0.2405,
    is_bottleneck: true,
    cycle_ratio: 1.38,
    delayed_units: 76,
    temperature_c: 88.4,
    vibration_mms: 4.82,
    power_kw: 28.6,
    tool_wear_min: 242,
    last_service: "2025-12-14",
    rca_status: "MECHANICAL_LOAD",
    rca_details: "Mechanical overload, torque surge, and spindle bearing degradation",
    shap_top_features: [
      { feature: "torque_nm", attribution: "+0.412", interpretation: "Severe cutting torque resistance" },
      { feature: "tool_wear_min", attribution: "+0.285", interpretation: "Extended tool wear exacerbating load" },
      { feature: "process_temp_k", attribution: "+0.198", interpretation: "Spindle bearing thermal dissipation deficit" },
    ],
    primary_recommendation: "INSPECT_SPINDLE_BEARING",
    recommendation_urgency: "IMMEDIATE",
    financial_realized_loss: 73062.28,
    financial_gross_exposure: 97382.28,
  },
  {
    machine_id: "M3",
    name: "Precision Grinder 03",
    type: "SURFACE_GRINDER",
    status: "HEALTHY",
    health_score: 97.47,
    failure_probability: 0.02,
    anomaly_score: 0.038,
    anomaly_threshold: 0.2405,
    is_bottleneck: false,
    cycle_ratio: 0.95,
    delayed_units: 0,
    temperature_c: 38.1,
    vibration_mms: 0.62,
    power_kw: 9.8,
    tool_wear_min: 40,
    last_service: "2026-01-12",
    rca_status: "NOMINAL",
    primary_recommendation: "CONTINUE_NOMINAL_MONITORING",
  },
  {
    machine_id: "M4",
    name: "Gear Hobber Machine 04",
    type: "GEAR_HOBBER",
    status: "HEALTHY",
    health_score: 97.47,
    failure_probability: 0.02,
    anomaly_score: 0.042,
    anomaly_threshold: 0.2405,
    is_bottleneck: false,
    cycle_ratio: 1.01,
    delayed_units: 0,
    temperature_c: 44.0,
    vibration_mms: 0.91,
    power_kw: 16.5,
    tool_wear_min: 65,
    last_service: "2026-01-08",
    rca_status: "NOMINAL",
    primary_recommendation: "CONTINUE_NOMINAL_MONITORING",
  },
  {
    machine_id: "M5",
    name: "Automated Inspection CMM 05",
    type: "CMM_INSPECTION",
    status: "HEALTHY",
    health_score: 97.47,
    failure_probability: 0.02,
    anomaly_score: 0.035,
    anomaly_threshold: 0.2405,
    is_bottleneck: false,
    cycle_ratio: 0.92,
    delayed_units: 0,
    temperature_c: 24.5,
    vibration_mms: 0.21,
    power_kw: 4.2,
    tool_wear_min: 10,
    last_service: "2026-01-15",
    rca_status: "NOMINAL",
    primary_recommendation: "CONTINUE_NOMINAL_MONITORING",
  },
];

export const MOCK_INVENTORY = [
  {
    sku_id: "SKU_SPINDLE_BEARING_M2",
    name: "Angular Contact Spindle Bearing (M2)",
    category: "CRITICAL_SPARE",
    target_machine: "M2",
    observed_stock: 2.0,
    safety_stock: 1.134,
    reorder_point: 1.367,
    unit_cost_inr: 4500.0,
    supplier_lead_time_days: 7.0,
    eoq: 12.0,
    projected_post_action_stock: 1.0,
    is_safety_stock_breached: true,
    action_required: "EXPEDITE_CRITICAL_SPARE",
  },
  {
    sku_id: "SKU_CARBIDE_INSERT_01",
    name: "TiN Coated Carbide Turning Inserts (10-pk)",
    category: "TOOLING",
    target_machine: "M1",
    observed_stock: 15.0,
    safety_stock: 4.5,
    reorder_point: 8.0,
    unit_cost_inr: 850.0,
    supplier_lead_time_days: 3.0,
    eoq: 25.0,
    projected_post_action_stock: 15.0,
    is_safety_stock_breached: false,
    action_required: "NOMINAL_MONITORING",
  },
  {
    sku_id: "SKU_SYNTH_LUBRICANT_ISO68",
    name: "ISO VG 68 Synthetic Guideway Oil (20L)",
    category: "CONSUMABLE",
    target_machine: "FLEET",
    observed_stock: 8.0,
    safety_stock: 3.0,
    reorder_point: 5.0,
    unit_cost_inr: 3200.0,
    supplier_lead_time_days: 2.0,
    eoq: 10.0,
    projected_post_action_stock: 8.0,
    is_safety_stock_breached: false,
    action_required: "NOMINAL_MONITORING",
  },
];

export const MOCK_SIMULATION_SCENARIOS = [
  {
    scenario_id: "SCEN_M2_A_BASELINE",
    name: "Scenario A: Unmitigated Progression",
    interventions: ["None"],
    assumptions: "Unplanned spindle seizure progression (Day 22 halt MAINT_0003)",
    avoided_loss_inr: 0.0,
    projected_post_action_stock: 2.0,
    remaining_gross_exposure_inr: 97382.28,
    epistemic_status: "CONTROLLED_SYNTHETIC",
  },
  {
    scenario_id: "SCEN_M2_B_INSPECT",
    name: "Scenario B: INSPECT_SPINDLE_BEARING",
    interventions: ["INSPECT_SPINDLE_BEARING"],
    assumptions: "30m planned maintenance stoppage avoids 150m emergency halt; consumes 1 spare",
    avoided_loss_inr: 9420.0,
    projected_post_action_stock: 1.0,
    remaining_gross_exposure_inr: 87962.28,
    epistemic_status: "PROJECTED",
  },
  {
    scenario_id: "SCEN_M2_C_INSPECT_EXPEDITE",
    name: "Scenario C: Inspection + Spare Expedite",
    interventions: ["INSPECT_SPINDLE_BEARING", "EXPEDITE_CRITICAL_SPARE"],
    assumptions: "Preempts halt + triggers PO for 12 spares under 7-day supplier lead time",
    avoided_loss_inr: 9420.0,
    projected_post_action_stock: 1.0,
    remaining_gross_exposure_inr: 87962.28,
    epistemic_status: "PROJECTED",
  },
  {
    scenario_id: "SCEN_M2_D_FLOW_MITIGATION",
    name: "Scenario D: Flow Rebalancing (Optimal)",
    interventions: ["REDUCE_MACHINE_FEED_RATE", "RESCHEDULE_PENDING_JOBS"],
    assumptions: "Offloads queued batches; cuts delayed throughput from 76 to 15 units",
    avoided_loss_inr: 19520.0,
    projected_post_action_stock: 2.0,
    remaining_gross_exposure_inr: 77862.28,
    epistemic_status: "PROJECTED",
  },
  {
    scenario_id: "SCEN_M2_E_FULL_PORTFOLIO",
    name: "Scenario E: Full Combined Portfolio",
    interventions: ["INSPECT_SPINDLE_BEARING", "REDUCE_MACHINE_FEED_RATE", "RESCHEDULE_PENDING_JOBS", "EXPEDITE_CRITICAL_SPARE"],
    assumptions: "Eliminates downtime halt + clears bottleneck backlog + reorders buffer",
    avoided_loss_inr: 28940.0,
    projected_post_action_stock: 1.0,
    remaining_gross_exposure_inr: 68442.28,
    epistemic_status: "PROJECTED",
  },
];

export const MOCK_RECOMMENDATIONS = [
  {
    rule_id: "R-M01",
    machine_id: "M2",
    category: "MAINTENANCE",
    action: "INSPECT_SPINDLE_BEARING",
    priority: "CRITICAL",
    urgency: "IMMEDIATE",
    reason: "Failure probability 0.9959 breaches 0.91 threshold; PCA anomaly score 0.35 breaches 0.2405; RCA = MECHANICAL_LOAD.",
    impact: "Preempts uncommanded spindle seizure, replacing 150m emergency breakdown with 30m planned service.",
    epistemic_status: "CONTROLLED_SYNTHETIC",
  },
  {
    rule_id: "R-I01",
    machine_id: "M2",
    category: "INVENTORY",
    action: "EXPEDITE_CRITICAL_SPARE",
    priority: "HIGH",
    urgency: "SAME_DAY",
    reason: "Consuming 1 bearing for M2 reduces stock to 1.0 unit, breaching 1.134 safety stock buffer under 7-day lead time.",
    impact: "Replenishes critical spare buffer to protect subsequent production cycles.",
    epistemic_status: "CONTROLLED_SYNTHETIC",
  },
  {
    rule_id: "R-P01",
    machine_id: "M2",
    category: "PRODUCTION_FLOW",
    action: "REDUCE_MACHINE_FEED_RATE",
    priority: "HIGH",
    urgency: "SAME_DAY",
    reason: "Machine M2 is an active bottleneck with cycle ratio 1.38 and 76 delayed units.",
    impact: "Stabilizes mechanical torque stress while relieving downstream starvation.",
    epistemic_status: "CONTROLLED_SYNTHETIC",
  },
];
