"""initial_schema

Revision ID: 49835d070f24
Revises: 
Create Date: 2026-09-13 14:55:29.357478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49835d070f24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_forecasting_results',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_series', sa.String(length=50), nullable=False),
    sa.Column('forecast_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index('idx_forecast_series_time', 'ai_forecasting_results', ['target_series', 'forecast_timestamp'], unique=False)
    op.create_index(op.f('ix_ai_forecasting_results_target_series'), 'ai_forecasting_results', ['target_series'], unique=False)
    op.create_table('factories',
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('factory_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('factory_id')
    )
    op.create_index(op.f('ix_factories_factory_code'), 'factories', ['factory_code'], unique=True)
    op.create_index(op.f('ix_factories_factory_id'), 'factories', ['factory_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('unit_cost_inr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=True)
    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.String(length=50), nullable=False),
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('sku_id', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Float(), nullable=False),
    sa.Column('unit_cost_inr', sa.Float(), nullable=False),
    sa.Column('reorder_quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_stock >= 0.0', name='chk_inv_current_stock_non_negative'),
    sa.CheckConstraint('reorder_point >= 0.0', name='chk_inv_reorder_point_non_negative'),
    sa.CheckConstraint('safety_stock >= 0.0', name='chk_inv_safety_stock_non_negative'),
    sa.CheckConstraint('unit_cost_inr >= 0.0', name='chk_inv_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.factory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index('idx_inv_sku', 'inventory_items', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_factory_id'), 'inventory_items', ['factory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku_id'), 'inventory_items', ['sku_id'], unique=True)
    op.create_table('machines',
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('design_cycle_time_sec', sa.Float(), nullable=False),
    sa.Column('baseline_power_kw', sa.Float(), nullable=False),
    sa.Column('baseline_vibration_mms', sa.Float(), nullable=False),
    sa.Column('alert_vibration_mms', sa.Float(), nullable=False),
    sa.Column('critical_vibration_mms', sa.Float(), nullable=False),
    sa.Column('rated_capacity_units_per_hour', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('critical_vibration_mms > alert_vibration_mms', name='chk_machine_vibration_order'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.factory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_index('idx_machine_factory_status', 'machines', ['factory_id', 'status'], unique=False)
    op.create_index(op.f('ix_machines_factory_id'), 'machines', ['factory_id'], unique=False)
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=False)
    op.create_table('ai_anomaly_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('detector_name', sa.String(length=100), nullable=False),
    sa.Column('anomaly_status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('idx_anomaly_machine_time', 'ai_anomaly_results', ['machine_id', 'timestamp'], unique=False)
    op.create_index('idx_anomaly_status', 'ai_anomaly_results', ['anomaly_status'], unique=False)
    op.create_index(op.f('ix_ai_anomaly_results_machine_id'), 'ai_anomaly_results', ['machine_id'], unique=False)
    op.create_table('ai_bottleneck_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bottleneck_status', sa.String(length=30), nullable=False),
    sa.Column('bottleneck_probability', sa.Float(), nullable=False),
    sa.Column('target_metric', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('idx_bottleneck_machine_time', 'ai_bottleneck_results', ['machine_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_bottleneck_results_machine_id'), 'ai_bottleneck_results', ['machine_id'], unique=False)
    op.create_table('ai_factory_health_scores',
    sa.Column('health_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=True),
    sa.Column('factory_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('health_state', sa.String(length=30), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('vibration_health', sa.Float(), nullable=False),
    sa.Column('temperature_health', sa.Float(), nullable=False),
    sa.Column('cycle_efficiency_health', sa.Float(), nullable=False),
    sa.Column('maintenance_health', sa.Float(), nullable=False),
    sa.Column('diagnostic_modifier', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('health_score >= 0.0 AND health_score <= 100.0', name='chk_health_score_range'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.factory_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('health_id')
    )
    op.create_index('idx_health_machine_time', 'ai_factory_health_scores', ['machine_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_factory_health_scores_factory_id'), 'ai_factory_health_scores', ['factory_id'], unique=False)
    op.create_index(op.f('ix_ai_factory_health_scores_machine_id'), 'ai_factory_health_scores', ['machine_id'], unique=False)
    op.create_table('ai_pdm_predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('prediction_class', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('failure_probability >= 0.0 AND failure_probability <= 1.0', name='chk_pdm_prob_range'),
    sa.CheckConstraint('prediction_class IN (0, 1)', name='chk_pdm_class_binary'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_pdm_machine_time', 'ai_pdm_predictions', ['machine_id', 'prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_ai_pdm_predictions_machine_id'), 'ai_pdm_predictions', ['machine_id'], unique=False)
    op.create_table('ai_rca_results',
    sa.Column('rca_id', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('primary_cause', sa.String(length=150), nullable=False),
    sa.Column('cause_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('evidence_strength', sa.String(length=30), nullable=False),
    sa.Column('evidence_details', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rca_id')
    )
    op.create_index('idx_rca_machine_time', 'ai_rca_results', ['machine_id', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_ai_rca_results_machine_id'), 'ai_rca_results', ['machine_id'], unique=False)
    op.create_index(op.f('ix_ai_rca_results_rca_id'), 'ai_rca_results', ['rca_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('recommendation_id', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('evidence_strength', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_references', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index('idx_rec_machine_priority', 'ai_recommendations', ['machine_id', 'priority'], unique=False)
    op.create_index('idx_rec_status', 'ai_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_machine_id'), 'ai_recommendations', ['machine_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_recommendation_id'), 'ai_recommendations', ['recommendation_id'], unique=False)
    op.create_table('ai_shap_explanations',
    sa.Column('explanation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_ref_id', sa.String(length=100), nullable=True),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    op.create_index('idx_shap_machine_rank', 'ai_shap_explanations', ['machine_id', 'ranking'], unique=False)
    op.create_index('idx_shap_ref', 'ai_shap_explanations', ['prediction_ref_id'], unique=False)
    op.create_index(op.f('ix_ai_shap_explanations_machine_id'), 'ai_shap_explanations', ['machine_id'], unique=False)
    op.create_index(op.f('ix_ai_shap_explanations_prediction_ref_id'), 'ai_shap_explanations', ['prediction_ref_id'], unique=False)
    op.create_table('finance_loss_records',
    sa.Column('loss_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loss_type', sa.String(length=50), nullable=False),
    sa.Column('downtime_minutes', sa.Float(), nullable=False),
    sa.Column('downtime_loss_inr', sa.Float(), nullable=False),
    sa.Column('scrap_loss_inr', sa.Float(), nullable=False),
    sa.Column('rework_loss_inr', sa.Float(), nullable=False),
    sa.Column('emergency_labor_loss_inr', sa.Float(), nullable=False),
    sa.Column('energy_loss_inr', sa.Float(), nullable=False),
    sa.Column('opportunity_cost_inr', sa.Float(), nullable=False),
    sa.Column('total_loss_inr', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loss_id')
    )
    op.create_index('idx_loss_machine_type', 'finance_loss_records', ['machine_id', 'loss_type'], unique=False)
    op.create_index('idx_loss_timestamp', 'finance_loss_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_finance_loss_records_machine_id'), 'finance_loss_records', ['machine_id'], unique=False)
    op.create_table('machine_telemetry_snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vibration_mms', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('ambient_temperature_c', sa.Float(), nullable=True),
    sa.Column('rotational_speed_rpm', sa.Float(), nullable=True),
    sa.Column('torque_nm', sa.Float(), nullable=True),
    sa.Column('sound_db', sa.Float(), nullable=True),
    sa.Column('power_consumption_kw', sa.Float(), nullable=True),
    sa.Column('oil_level_pct', sa.Float(), nullable=True),
    sa.Column('coolant_level_pct', sa.Float(), nullable=True),
    sa.Column('tool_wear_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index('idx_telemetry_machine_time', 'machine_telemetry_snapshots', ['machine_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_machine_telemetry_snapshots_machine_id'), 'machine_telemetry_snapshots', ['machine_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('maintenance_id', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('failure_mode', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('technician', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_decision_input', sa.Boolean(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_index('idx_maint_decision_input', 'maintenance_records', ['machine_id', 'is_decision_input'], unique=False)
    op.create_index('idx_maint_machine_time', 'maintenance_records', ['machine_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_maintenance_records_machine_id'), 'maintenance_records', ['machine_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_id'), 'maintenance_records', ['maintenance_id'], unique=False)
    op.create_table('production_jobs',
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cycle_time', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=False),
    sa.Column('scrap_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completed_quantity >= 0', name='chk_job_completed_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='chk_job_quantity_non_negative'),
    sa.CheckConstraint('scrap_quantity >= 0', name='chk_job_scrap_non_negative'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.factory_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_job_factory_status', 'production_jobs', ['factory_id', 'status'], unique=False)
    op.create_index('idx_job_machine_start', 'production_jobs', ['machine_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_production_jobs_factory_id'), 'production_jobs', ['factory_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_job_id'), 'production_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_machine_id'), 'production_jobs', ['machine_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_product_id'), 'production_jobs', ['product_id'], unique=False)
    op.create_table('sensors',
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('sensor_code', sa.String(length=50), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sampling_interval', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index(op.f('ix_sensors_machine_id'), 'sensors', ['machine_id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_id'), 'sensors', ['sensor_id'], unique=False)
    op.create_table('simulation_scenarios',
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('decision_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intervention_list', sa.Text(), nullable=False),
    sa.Column('projected_metrics', sa.Text(), nullable=False),
    sa.Column('financial_projection', sa.Text(), nullable=False),
    sa.Column('configured_assumptions', sa.Text(), nullable=False),
    sa.Column('temporal_semantics', sa.String(length=60), nullable=False),
    sa.Column('epistemic_status', sa.String(length=60), nullable=False),
    sa.Column('diagnostic_kpi_status', sa.String(length=50), nullable=False),
    sa.Column('provenance', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index('idx_sim_machine_cutoff', 'simulation_scenarios', ['machine_id', 'decision_cutoff'], unique=False)
    op.create_index(op.f('ix_simulation_scenarios_machine_id'), 'simulation_scenarios', ['machine_id'], unique=False)
    op.create_index(op.f('ix_simulation_scenarios_scenario_id'), 'simulation_scenarios', ['scenario_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=True),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality_flag', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index('idx_reading_machine_time', 'sensor_readings', ['machine_id', 'timestamp'], unique=False)
    op.create_index('idx_reading_sensor_time', 'sensor_readings', ['sensor_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_machine_id'), 'sensor_readings', ['machine_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_machine_id'), table_name='sensor_readings')
    op.drop_index('idx_reading_sensor_time', table_name='sensor_readings')
    op.drop_index('idx_reading_machine_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_simulation_scenarios_scenario_id'), table_name='simulation_scenarios')
    op.drop_index(op.f('ix_simulation_scenarios_machine_id'), table_name='simulation_scenarios')
    op.drop_index('idx_sim_machine_cutoff', table_name='simulation_scenarios')
    op.drop_table('simulation_scenarios')
    op.drop_index(op.f('ix_sensors_sensor_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_machine_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_production_jobs_product_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_machine_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_job_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_factory_id'), table_name='production_jobs')
    op.drop_index('idx_job_machine_start', table_name='production_jobs')
    op.drop_index('idx_job_factory_status', table_name='production_jobs')
    op.drop_table('production_jobs')
    op.drop_index(op.f('ix_maintenance_records_maintenance_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_machine_id'), table_name='maintenance_records')
    op.drop_index('idx_maint_machine_time', table_name='maintenance_records')
    op.drop_index('idx_maint_decision_input', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_machine_telemetry_snapshots_machine_id'), table_name='machine_telemetry_snapshots')
    op.drop_index('idx_telemetry_machine_time', table_name='machine_telemetry_snapshots')
    op.drop_table('machine_telemetry_snapshots')
    op.drop_index(op.f('ix_finance_loss_records_machine_id'), table_name='finance_loss_records')
    op.drop_index('idx_loss_timestamp', table_name='finance_loss_records')
    op.drop_index('idx_loss_machine_type', table_name='finance_loss_records')
    op.drop_table('finance_loss_records')
    op.drop_index(op.f('ix_ai_shap_explanations_prediction_ref_id'), table_name='ai_shap_explanations')
    op.drop_index(op.f('ix_ai_shap_explanations_machine_id'), table_name='ai_shap_explanations')
    op.drop_index('idx_shap_ref', table_name='ai_shap_explanations')
    op.drop_index('idx_shap_machine_rank', table_name='ai_shap_explanations')
    op.drop_table('ai_shap_explanations')
    op.drop_index(op.f('ix_ai_recommendations_recommendation_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_machine_id'), table_name='ai_recommendations')
    op.drop_index('idx_rec_status', table_name='ai_recommendations')
    op.drop_index('idx_rec_machine_priority', table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ai_rca_results_rca_id'), table_name='ai_rca_results')
    op.drop_index(op.f('ix_ai_rca_results_machine_id'), table_name='ai_rca_results')
    op.drop_index('idx_rca_machine_time', table_name='ai_rca_results')
    op.drop_table('ai_rca_results')
    op.drop_index(op.f('ix_ai_pdm_predictions_machine_id'), table_name='ai_pdm_predictions')
    op.drop_index('idx_pdm_machine_time', table_name='ai_pdm_predictions')
    op.drop_table('ai_pdm_predictions')
    op.drop_index(op.f('ix_ai_factory_health_scores_machine_id'), table_name='ai_factory_health_scores')
    op.drop_index(op.f('ix_ai_factory_health_scores_factory_id'), table_name='ai_factory_health_scores')
    op.drop_index('idx_health_machine_time', table_name='ai_factory_health_scores')
    op.drop_table('ai_factory_health_scores')
    op.drop_index(op.f('ix_ai_bottleneck_results_machine_id'), table_name='ai_bottleneck_results')
    op.drop_index('idx_bottleneck_machine_time', table_name='ai_bottleneck_results')
    op.drop_table('ai_bottleneck_results')
    op.drop_index(op.f('ix_ai_anomaly_results_machine_id'), table_name='ai_anomaly_results')
    op.drop_index('idx_anomaly_status', table_name='ai_anomaly_results')
    op.drop_index('idx_anomaly_machine_time', table_name='ai_anomaly_results')
    op.drop_table('ai_anomaly_results')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_factory_id'), table_name='machines')
    op.drop_index('idx_machine_factory_status', table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_inventory_items_sku_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_factory_id'), table_name='inventory_items')
    op.drop_index('idx_inv_sku', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_factories_factory_id'), table_name='factories')
    op.drop_index(op.f('ix_factories_factory_code'), table_name='factories')
    op.drop_table('factories')
    op.drop_index(op.f('ix_ai_forecasting_results_target_series'), table_name='ai_forecasting_results')
    op.drop_index('idx_forecast_series_time', table_name='ai_forecasting_results')
    op.drop_table('ai_forecasting_results')
    # ### end Alembic commands ###
